import { NextResponse } from "next/server"

const featuredCars = [
    {
        id: 1,
        name: "Tesla Model S",
        price: 89990,
        image: "/images/compositor.jpg",
        category: "Electric",
        year: 2023,
        mileage: 0,
        fuelType: "Electric",
        transmission: "Automatic",
        seats: 5,
        featured: true,
        link: "/cars/tesla-model-s",
    },
    {
        id: 2,
        name: "BMW 5 Series",
        price: 54990,
        image: "/placeholder.svg?height=300&width=400",
        category: "Sedan",
        year: 2023,
        mileage: 0,
        fuelType: "Hybrid",
        transmission: "Automatic",
        seats: 5,
        featured: true,
        link: "/cars/bmw-5-series",
    },
    {
        id: 3,
        name: "Mercedes-Benz GLE",
        price: 64990,
        image: "/placeholder.svg?height=300&width=400",
        category: "SUV",
        year: 2023,
        mileage: 0,
        fuelType: "Petrol",
        transmission: "Automatic",
        seats: 7,
        featured: true,
        link: "/cars/mercedes-benz-gle",
    },
    {
        id: 4,
        name: "Audi e-tron GT",
        price: 99990,
        image: "/placeholder.svg?height=300&width=400",
        category: "Electric",
        year: 2023,
        mileage: 0,
        fuelType: "Electric",
        transmission: "Automatic",
        seats: 4,
        featured: true,
        link: "/cars/audi-e-tron-gt",
    },
    {
        id: 5,
        name: "Porsche 911",
        price: 114990,
        image: "/placeholder.svg?height=300&width=400",
        category: "Sports",
        year: 2023,
        mileage: 0,
        fuelType: "Petrol",
        transmission: "Automatic",
        seats: 2,
        featured: true,
        link: "/cars/porsche-911",
    },
    {
        id: 6,
        name: "Range Rover Sport",
        price: 79990,
        image: "/placeholder.svg?height=300&width=400",
        category: "SUV",
        year: 2023,
        mileage: 0,
        fuelType: "Diesel",
        transmission: "Automatic",
        seats: 5,
        featured: true,
        link: "/cars/range-rover-sport",
    },
]

export async function GET() {
    return NextResponse.json(featuredCars)
}
